on: push
name: Deploy FTP
jobs:
  web-deploy:
    name: Deploy automatico via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el codigo mas recicente
        uses: actions/checkout@v3

      - name: Sincronizar archivos con el servidor
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ./
